#!/usr/bin/env python3
import argparse
import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

from rich.console import Console

console = Console()

def utc_now():
  return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

def main():
  ap = argparse.ArgumentParser()
  ap.add_argument("--out", required=True, help="Output directory")
  ap.add_argument("--toy", action="store_true", help="Build a toy sample bundle")
  args = ap.parse_args()

  out = Path(args.out)
  out.mkdir(parents=True, exist_ok=True)

  meta = {
    "bundle_id": f"BUNDLE-{utc_now()}",
    "created_at": utc_now(),
    "mode": "toy" if args.toy else "custom"
  }
  (out / "bundle.meta.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")

  if args.toy:
    # Copy example evidence + graph
    src_evidence = Path("artifacts/examples/evidence_items.json")
    src_graph = Path("graphs/toy/toy_graph.json")
    dst_dir = out / "inputs"
    dst_dir.mkdir(exist_ok=True)
    shutil.copy2(src_evidence, dst_dir / src_evidence.name)
    shutil.copy2(src_graph, dst_dir / src_graph.name)

    # Create a minimal report placeholder
    report = out / "gap_report.md"
    report.write_text(
      "# Gap Report (toy)\n\n"
      "- This is a placeholder report generated by bundle_build.py\n"
      "- Replace with real appraisal logic and organization-specific controls.\n",
      encoding="utf-8"
    )

  console.print(f"[green]Bundle created at[/green] {out}")

if __name__ == "__main__":
  main()
